// <auto-generated />
using ExpenseTracker.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpenseTracker.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221206024549_bh")]
    partial class bh
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ExpenseTracker.Models.CauThu", b =>
                {
                    b.Property<int>("IdCT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCT"), 1L, 1);

                    b.Property<string>("SoAo")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ViTri")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdCT");

                    b.ToTable("CauThus");

                    b.HasData(
                        new
                        {
                            IdCT = 1,
                            SoAo = "10",
                            Ten = "LIONEL MESSI",
                            Type = "Chinh",
                            ViTri = "TienVe"
                        },
                        new
                        {
                            IdCT = 2,
                            SoAo = "7",
                            Ten = "CRISTIANO RONALDO",
                            Type = "Chinh",
                            ViTri = "TienVe"
                        },
                        new
                        {
                            IdCT = 3,
                            SoAo = "9",
                            Ten = "CT-003",
                            Type = "Chinh",
                            ViTri = "TienVe"
                        });
                });

            modelBuilder.Entity("ExpenseTracker.Models.DoiBong", b =>
                {
                    b.Property<string>("MADOIBONG")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HLV")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SOCAUTHU")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TENQUOCGIA")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MADOIBONG");

                    b.ToTable("DoiBongs");
                });

            modelBuilder.Entity("ExpenseTracker.Models.Lich", b =>
                {
                    b.Property<int>("LichId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LichId"), 1L, 1);

                    b.Property<string>("SAN")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenDoi1")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenDoi2")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LichId");

                    b.ToTable("Lichs");
                });
#pragma warning restore 612, 618
        }
    }
}
