// <auto-generated />
using System;
using ExpenseTracker.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpenseTracker.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221205125220_Tai")]
    partial class Tai
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ExpenseTracker.Models.Category", b =>
                {
                    b.Property<int>("RapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RapId"), 1L, 1);

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenRap")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RapId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            RapId = 1,
                            DiaChi = "639",
                            TenRap = "AnDuongVuong",
                            Type = "Expense"
                        });
                });

            modelBuilder.Entity("ExpenseTracker.Models.DSPhim", b =>
                {
                    b.Property<int>("PhimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhimId"), 1L, 1);

                    b.Property<string>("TenPhim")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ThoiLuong")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PhimId");

                    b.ToTable("DSPhims");

                    b.HasData(
                        new
                        {
                            PhimId = 1,
                            TenPhim = "AnDuongVuong",
                            ThoiLuong = "639",
                            Type = "Expense"
                        });
                });

            modelBuilder.Entity("ExpenseTracker.Models.Lich", b =>
                {
                    b.Property<int>("LichId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LichId"), 1L, 1);

                    b.Property<string>("Giocongchieu")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenPhim")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenRap")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LichId");

                    b.ToTable("Lichs");

                    b.HasData(
                        new
                        {
                            LichId = 1,
                            Giocongchieu = "113h00",
                            TenPhim = "AnDuongVuong",
                            TenRap = "NhaHan",
                            Type = "Expense"
                        });
                });

            modelBuilder.Entity("ExpenseTracker.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"), 1L, 1);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryRapId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(75)");

                    b.Property<int>("RapId")
                        .HasColumnType("int");

                    b.HasKey("TransactionId");

                    b.HasIndex("CategoryRapId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("ExpenseTracker.Models.Transaction", b =>
                {
                    b.HasOne("ExpenseTracker.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryRapId");

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
